### ISSUE TITLE
Create image of database schema

### ISSUE THREAD

**Issue by timrobertson100** [Symbiota/Symbiota-deprecated#140]
It would be useful to have a visual of the database schema for Symbiota. Does one exist please, before I create one from the DDL.

Perhaps it could be committed somewhere?

Many thanks

**Comment by bdbrandt** [comment]
Hi Tim,

There are currently multiple active forks of Symbiota being developed right now, any of which may have slightly different database schemas. This original repo is a bit outdated, but [here is a link to a database schema image to one of the more currently maintained forks](https://github.com/greentheorystudio/Symbiota/blob/master/config/schema-1.0/db-schema-model.svg)

Cheers,
Ben

**Comment by timrobertson100** [comment]
Thanks Ben,
That’s ideal
