### ISSUE TITLE
Checklist polygon function

### ISSUE THREAD

**Issue by neilcobb** [Symbiota/Symbiota-deprecated#88]
need to query against made polygon repeatedly through time.  So I can make a polygon for an area and every six months have the option to re-query.  then I can remove any records that I do not like.

**Comment by Barkworth** [comment]
Identifying state boundaries for Mexico (and probably other countries) is very hard on the map provided. It is worse when one zooms in. Adding an option to upload a polygon file (?from a shp file) would be useful, particularly for those who understand geographic files.
